#!/usr/bin/env bash

hc() {
	herbstclient "$@"
}
 
polybar top &
#feh --bg-scale ~/Wallpapers/autumn &
dunst &
discord &
picom &
#nm-applet &
 
hc keyunbind --all
 
Mod=Mod4
myTerm=alacritty
myEditor=micro
 
# Spawning other programs
hc keybind $Mod-Return spawn $myTerm
hc keybind $Mod-space spawn rofi -show drun
hc keybind $Mod-Shift-p spawn pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo +5%
hc keybind $Mod-Shift-o spawn pactl set-sink-volume alsa_output.pci-0000_00_1b.0.analog-stereo -5%
 
# Important actions
hc keybind $Mod-Shift-q     quit
hc keybind $Mod-Shift-c     close
hc keybind $Mod-Shift-r     reload	
 
# Focus and movement with W,A,S,D
hc keybind $Mod-Left        focus left
hc keybind $Mod-Right       focus right
hc keybind $Mod-Up          focus up
hc keybind $Mod-Down        focus down
hc keybind $Mod-a           focus left
hc keybind $Mod-s           focus down
hc keybind $Mod-w           focus up
hc keybind $Mod-d           focus right
 
hc keybind $Mod-Shift-Left      shift left
hc keybind $Mod-Shift-Right     shift right
hc keybind $Mod-Shift-Up        shift up
hc keybind $Mod-Shift-Down      shift down
hc keybind $Mod-Shift-a         shift left
hc keybind $Mod-Shift-s         shift down
hc keybind $Mod-Shift-w         shift up
hc keybind $Mod-Shift-d         shift right
 
# Splitting
hc keybind $Mod-Alt-v       split bottom
hc keybind $Mod-Alt-h       split right
hc keybind $Mod-Alt-space   split explode
 
# Mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button3 zoom
hc mousebind $Mod-Button2 resize
 
# Resizing
resizestep=0.05
hc keybind $Mod-Alt-a       resize left +$resizestep
hc keybind $Mod-Alt-s       resize down +0.05
hc keybind $Mod-Alt-d       resize right +$resizestep
hc keybind $Mod-Alt-w       resize up +$resizestep
hc keybind $Mod-Alt-Left    resize left +$resizestep
hc keybind $Mod-Alt-Down    resize down +$resizestep
hc keybind $Mod-Alt-Right   resize right +$resizestep
hc keybind $Mod-Alt-Up      resize up +$resizestep
 
hc keybind $Mod-Alt-r           remove
hc keybind $Mod-f               floating toggle

# Add tags
tag_names=(Terminal Web Code Reference Music Chat Video)
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# Colours
background="#0f111b"
foreground="#ecf0c1"
purple="#7a5ccc"
green="#5ccc96"
 
# Common settings
hc set frame_gap                    10
hc set frame_padding                4
hc set window_gap                   5
hc set snap_gap                     15
hc set frame_border_active_color    ${green}
hc set frame_border_normal_color    ${background}
hc set frame_bg_transparent         1
hc set frame_bg_active_color        ${green}
hc set frame_bg_normal_color        ${background}
hc set raise_on_focus_temporarily   true
hc set default_frame_layout         grid
hc set smart_frame_surroundings     true
hc set auto_detect_monitors         true

# Attributes
hc attr theme.title_height 			0
hc attr theme.title_font			Hack Nerd Font:style=Regular:size=12
hc attr theme.padding_left 			4
hc attr theme.padding_right			4
hc attr theme.padding_top			4
hc attr theme.padding_bottom		4
hc attr theme.color					${background}
hc attr theme.active.color			${purple}
hc attr theme.normal.color 			${background}
hc attr theme.urgent.color			${background}
hc attr theme.active.title_color	${foreground}
hc attr theme.title_color 			${foreground}
hc attr theme.inner_width 			0
hc attr theme.inner_width			0
hc attr theme.inner_color			${background}
hc attr theme.border_width			0
hc attr theme.floating.border_width	0
hc attr theme.floating.outer_width	0
hc attr theme.floating.outer_color	${background}
hc attr theme.active.inner_color 	${background}
hc attr theme.urgent.inner_color 	${background}
hc attr theme.normal.inner_color 	${background}
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.active.outer_width	0
hc attr theme.background_color		${background}
# Rules
hc rule      --title=Discord --tag=Chat --focus=off
