#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII

bspc config border_width           4
bspc config window_gap             5
bspc config focus_follows_pointer  true
bspc config split_ratio            0.5
bspc config top_padding            40
bspc config left_padding           2
bspc config bottom_padding         2
bspc config right_padding          2

bspc config focused_border_color   "#7a5ccc"
bspc config normal_border_color    "#0f111b"
bspc config presel_feedback_color  "#5ccc96"

picom &
polybar top &
dunst &
